name: CI Build
on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
  execute:
    name: CI Build
    runs-on: ubuntu-latest
    container:
      image: "python:3.13.1-bookworm"
    steps:
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          # apt-get update
          # apt-get install -y -qq build-essential
          pip install uv==0.5.11
          export PYTHONPATH="$GITHUB_WORKSPACE"
          uv run invoke build
