name: Update Documentation
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch:
jobs:
  build_deploy_docs:
    name: Update documentation
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Install rust if not istalled
        run: rustup --help || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.43'
      - run: cd docs && mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
          publish_branch: gh-pages
